[versions]
springBoot = "4.0.8"
springDepMgmt = "1.1.7"
cucumber = "7.22.1"
jqwik = "1.9.3"
archunit = "1.4.1"
jsonSchema = "1.5.6"
junitPlatform = "1.11.4"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot-flyway = { module = "org.springframework.boot:spring-boot-flyway" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite" }
assertj-core = { module = "org.assertj:assertj-core" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
cucumber-spring = { module = "io.cucumber:cucumber-spring", version.ref = "cucumber" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchema" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dep-mgmt = { id = "io.spring.dependency-management", version.ref = "springDepMgmt" }
